### ISSUE TITLE
Output units are in bytes

### ISSUE THREAD

**Issue by desultory** [desultory/PyCPIO#3]
MiB would probably be better, maybe with the bytes in parentheses.

**Comment by SyedZain714** [comment]
@desultory Hi I hope you are well.
Can you elaborate a bit and also give a brief about the  library and how to set it up?

**Comment by desultory** [comment]
https://github.com/desultory/pycpio/blob/main/src/pycpio/writer/writer.py#L55

it's a simple change that can be made here (and in the compression method)

I encourage you to try to discover usage from the main file, and the pycpio.py file, from there it should be clear where these changes need to be made. If you need an explanation, please ask something specific.

This project is lacking a lot of documentation, but I've tried to comment the code reasonably and design it in a straightforward manner.

**Comment by SyedZain714** [comment]
I just want to know what this project is about

**Comment by desultory** [comment]
@SyedZain714 

pycpio is a cpio library written in python. I mostly use it for my initramfs generator project "UGRD". this project is designed to read and create CPIO archives.

**Comment by desultory** [comment]
this was fixed a while back
